theme: jekyll-theme-cayman
title: Accessible Audio Keyboard
description: An inexpensive predictive audio keyboard for people with communication disabilities.
show_downloads: true
include: CONTRIBUTING.md, LICENSE.md
